### ISSUE TITLE
Lab 3 Contributor 

### ISSUE THREAD

**Issue by nicoletorres1** [ivan-015/CS2302-nlp-trees#1]
I tested your code and it compiled. I like how elegant and fluid your program runs. It is easy to follow an understand your commenting as well as the way you named your variables. Overall I think you did a great job. It's really smart that you implemented the timer for the code and I never would have thought to import the AVL trees, I learned something new! Good job!

**Comment by ivan-015** [comment]
Thank you for the kind comments!
